# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.106</version>
#    <timestamp>2026-06-30T08:06:24.182Z</timestamp>
#    <hash>d35142823700d756</hash>
# </meta>

neoforge:
  - "/^neoforge$/m"
forge:
  - "/^forge$/m"
