# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.93</version>
#    <timestamp>2026-06-17T16:44:35.207Z</timestamp>
#    <hash>d35142823700d756</hash>
# </meta>

neoforge:
  - "/^neoforge$/m"
forge:
  - "/^forge$/m"
