# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.83</version>
#    <timestamp>2026-06-08T09:30:50.539Z</timestamp>
#    <hash>d35142823700d756</hash>
# </meta>

neoforge:
  - "/^neoforge$/m"
forge:
  - "/^forge$/m"
