kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mc_version=1.21.1
neoforge_version=21.1.219
parchment_mappings_version=2024.11.17

mod_id=arboretum
mod_version=0.0.0-dev
release_type=beta
mod_name=Arboretum
mod_author=possible_triangle
mod_description=Bigger & Fancier trees for more convincing forests

kotlin_forge_version=5.11.0

repository=voidshake/arboretum
modrinth_project_id=mB9gmqAh
maven_group=com.possible-triangle
